
scheme_dir="schemes"

[metaoptions]
internal_escape_char='\' #applies to text values within axbind files
wildcard_char='^' #representation of 'key' (i.e. char that is replaced with something, like in 'key_format', or 'SCHEME.functions.command'

#defaults
[options]
key_format='@^@'
escape_char='\' #will leave next char as-is always with no parsing (consumes this char)
