axbind_scheme='colors'

[bindings]
ok="green"
error="red"

[remaps.hex]
'green'="#00FF00"
'red'="#FF0000"
#functions are commands that remap ALL values based on a binary's stdout
#'^' represents the value pre-remap
[functions.wrapper]
shell='sh'
command='echo -n "Color(^)"'
