#any field/option specified in the MAIN tagfile (this) will apply to ALL groupfiles unless overriden
groups = [
    "mybindinggroup.toml",
    "mycolorgroup.toml",
]
#-- OR --
#'groups' and 'files' are mutually exclusive
files = [
    "myconfig.file",
]

# -- OR --
#files = [
#    {source="myconfig.file.axbind", dest="myconfig.file"}
#]
#'options' are taken directly from the main axbind config file, and are overriden here
#'options' specified in main tagfile are applied to all groups if 'groups' is specified, but are overriden by options specified in the group files
[options]
keyformat='@@a@@' #'a' is placeholder for key, to use an actual 'a' use '\a'

